### ISSUE TITLE
Multiple Connection Object

### ISSUE THREAD

**Issue by mahavirjain** [strophe/strophejs#94] opened 2014-12-01 05:14 UTC
I want to use multiple connection object on same webpage, each connection for a separate user.

The problem i am facing is i am able to connect users to multiple connection objects but they are not working properly. Kindle provide a solution how can is use Strophe for multiple connections on same page.

Here is code snippet : 

var chat_connection={};

     chat_connection[v.username] = new Strophe.Connection(BOSH_SERVICE);
    chat_connection[v.username].connect(v.username+"@"+chat_serverName,v.password,function(status){
    if (status == Strophe.Status.CONNECTING) {
    } else if (status == Strophe.Status.CONNFAIL) {
    } else if (status == Strophe.Status.DISCONNECTING) {
    } else if (status == Strophe.Status.DISCONNECTED) {
    } 
else if(status == Strophe.Status.CONNECTED) {
   this.addHandler(receiveMessage, null, 'message', null, null,  null); 
  this.send($pres().tree());
    }
      });

**Comment by jcbrand** [comment] 2015-01-17 14:10
> able to connect users to multiple connection objects but they are not working properly

In what way are they not working properly? What exactly is the problem?

**Comment by jcbrand** [comment] 2015-02-04 09:12
Closing due to inaction.

**Closed by jcbrand** 2015-02-04 09:12 UTC

**Comment by Gordin** [comment] 2015-02-04 09:42
I fixed using multiple connections on one site a while ago, probably it's just not in the current release yet.

**Comment by jcbrand** [comment] 2015-02-04 09:50
Does that mean it'll be included in the next (1.2.0) release, or is it something which still needs to be merged into master?

**Comment by Gordin** [comment] 2015-02-04 11:50
It's already merged in master. I think this is a duplicate of https://github.com/strophe/strophejs/issues/53
