### ISSUE TITLE
Multiple onMessage triggered when onPresence handler triggered

### ISSUE THREAD

**Issue by NehaaSaini** [strophe/strophejs#317] opened 2019-02-04 06:46 UTC
We are using Strophe to build live chat in our react app and  facing some issues while doing so.

I am sending a message while i am connected on xmpp server. When I am sending  message from user 'a' to user 'b' when both users are connected. User 'a' sends a message "hi" to user 'b' the multiple onMessage handler whenever onPresence triggered  on user 'b' due to this user 'b' get multiple "hi". Please provide some suggestions into this, as it really hampered our code.

**Comment by jcbrand** [comment] 2019-02-05 19:33
Duplicate of #316

**Closed by jcbrand** 2019-02-05 19:33 UTC
