### ISSUE TITLE
window is not defined on V1.4.0

### ISSUE THREAD

**Issue by SravanKumarNangunoori** [strophe/strophejs#367] opened 2020-11-05 20:43 UTC
kuna/node_modules/strophe.js/dist/strophe.common.js:4834
      if (window.XMLHttpRequest) {
      ^

ReferenceError: window is not defined
    at Request._newXHR (/Users/sravankumarnangunoori/Desktop/serg/akuna/node_modules/strophe.js/dist/strophe.common.js:4834:7)
    at new Request (/Users/sravankumarnangunoori/Desktop/serg/akuna/node_modules/strophe.js/dist/strophe.common.js:4771:21)
    at Bosh._connect (/Users/sravankumarnangunoori/Desktop/serg/akuna/node_modules/strophe.js/dist/strophe.common.js:4977:27)
    at Connection.connect (/Users/sravankumarnangunoori/Desktop/serg/akuna/node_modules/strophe.js/dist/strophe.common.js:2619:19)
    at Object.<anonymous> (/Users/sravankumarnangunoori/Desktop/serg/akuna/test.js:17:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by jcbrand** [comment] 2020-11-06 08:40
Duplicate of #201 and already fixed in master.

**Closed by jcbrand** 2020-11-06 08:40 UTC

**Comment by SravanKumarNangunoori** [comment] 2020-11-06 14:12
@jcbrand  Is this available n the version 1.4.0

**Comment by jcbrand** [comment] 2020-11-06 14:25
No, it'll be fixed in the next release.

**Comment by SravanKumarNangunoori** [comment] 2020-11-06 15:07
Thank you @jcbrand , any ETA on the next version
